#!/bin/sh
# -*- coding: utf-8 -*-


print_usage() {
    echo "Usage: ./run command"
    echo "Commands:"
    echo "    viewer"
    echo "        Open the data viewer"
    echo ""
}

if [ $# -eq 0 ]; then
    print_usage
else
    if [ $1 == "viewer" ]; then
        python2 reid/utils/data_viewer.py
    else
        print_usage
    fi
fi

