#!/usr/bin/python2
# -*- coding: utf-8 -*-

datasets = ['CUHK', 'CUHKL', 'CUHKD', 'GRID', 'PRID', 'VIPeR', '3DPeS', 'SARC3D']

names = [
    'genderFemale',
    'genderMale',
    'ageChild',
    'ageYouth',
    'ageMiddle',
    'ageElder',
    'raceAsian',
    'raceBlack',
    'raceWhite',
    'accessoryCap',
    'accessoryFaceMask',
    'accessoryGlasses',
    'accessoryHairBand',
    'accessoryHat',
    'accessoryHeadphone',
    'accessoryKerchief',
    'accessoryMuffler',
    'accessorySunglasses',
    'accessoryTie',
    'accessoryOther',
    'accessoryNothing',
    'carryingBackpack',
    'carryingHandbag',
    'carryingLuggageCase',
    'carryingOutwear',
    'carryingShoppingBag',
    'carryingShoulderBag',
    'carryingUmbrella',
    'carryingOther',
    'carryingNothing',
    'upperBodyBlack',
    'upperBodyBlue',
    'upperBodyBrown',
    'upperBodyGreen',
    'upperBodyGrey',
    'upperBodyOrange',
    'upperBodyPink',
    'upperBodyPurple',
    'upperBodyRed',
    'upperBodyWhite',
    'upperBodyYellow',
    'upperBodyOtherColor',
    'upperBodyCoat',
    'upperBodyDownCoat',
    'upperBodyDress',
    'upperBodyJacket',
    'upperBodyShirt',
    'upperBodySweater',
    'upperBodySuit',
    'upperBodyTshirt',
    'upperBodyOtherStyle',
    'upperBodyNoSleeve',
    'upperBodyShortSleeve',
    'upperBodyLongSleeve',
    'upperBodyLogo',
    'upperBodyPlaid',
    'upperBodyHStripe',
    'upperBodyVStripe',
    'upperBodyOtherTexture',
    'upperBodyNoTexture',
    'lowerBodyBlack',
    'lowerBodyBlue',
    'lowerBodyBrown',
    'lowerBodyGreen',
    'lowerBodyGrey',
    'lowerBodyOrange',
    'lowerBodyPink',
    'lowerBodyPurple',
    'lowerBodyRed',
    'lowerBodyWhite',
    'lowerBodyYellow',
    'lowerBodyOtherColor',
    'lowerBodyJeans',
    'lowerBodyPants',
    'lowerBodySports',
    'lowerBodySkirt',
    'lowerBodyStockings',
    'lowerBodySuit',
    'lowerBodyOtherStyle',
    'lowerBodyShort',
    'lowerBodyCapri',
    'lowerBodyLong',
    'lowerBodyLogo',
    'lowerBodyPlaid',
    'lowerBodyHStripe',
    'lowerBodyVStripe',
    'lowerBodyOtherTexture',
    'lowerBodyNoTexture',
    'hairBlack',
    'hairBlue',
    'hairBrown',
    'hairGreen',
    'hairGrey',
    'hairOrange',
    'hairPink',
    'hairPurple',
    'hairRed',
    'hairWhite',
    'hairYellow',
    'hairOtherColor',
    'hairBald',
    'hairBrushCut',
    'hairMidLength',
    'hairLong'
]

unival = [
    ['genderFemale', 'genderMale'],
    ['ageChild', 'ageYouth', 'ageMiddle', 'ageElder'],
    ['raceAsian', 'raceBlack', 'raceWhite'],
    ['upperBodyNoSleeve', 'upperBodyShortSleeve', 'upperBodyLongSleeve'],
    ['upperBodyLogo', 'upperBodyPlaid', 'upperBodyHStripe', 'upperBodyVStripe', 'upperBodyOtherTexture', 'upperBodyNoTexture'],
    ['lowerBodyBlack', 'lowerBodyBlue', 'lowerBodyBrown', 'lowerBodyGreen', 'lowerBodyGrey', 'lowerBodyOrange', 'lowerBodyPink', 'lowerBodyPurple', 'lowerBodyRed', 'lowerBodyWhite', 'lowerBodyYellow', 'lowerBodyOtherColor'],
    ['lowerBodyJeans', 'lowerBodyPants', 'lowerBodySports', 'lowerBodySkirt', 'lowerBodyStockings', 'lowerBodySuit', 'lowerBodyOtherStyle'],
    ['lowerBodyShort', 'lowerBodyCapri', 'lowerBodyLong'],
    ['lowerBodyLogo', 'lowerBodyPlaid', 'lowerBodyHStripe', 'lowerBodyVStripe', 'lowerBodyOtherTexture', 'lowerBodyNoTexture'],
    ['hairBlack', 'hairBlue', 'hairBrown', 'hairGreen', 'hairGrey', 'hairOrange', 'hairPink', 'hairPurple', 'hairRed', 'hairWhite', 'hairYellow', 'hairOtherColor'],
    ['hairBald', 'hairBrushCut', 'hairMidLength', 'hairLong']
]

unival_titles = [
    'Gender',
    'Age',
    'Race',
    'Upper Body Sleeve',
    'Upper Body Texture',
    'Lower Body Color',
    'Lower Body Style',
    'Lower Body Length',
    'Lower Body Texture',
    'Hair Color',
    'Hair Style'
]

multival = [
    ['accessoryCap', 'accessoryFaceMask', 'accessoryGlasses', 'accessoryHairBand', 'accessoryHat', 'accessoryHeadphone', 'accessoryKerchief', 'accessoryMuffler', 'accessorySunglasses', 'accessoryTie', 'accessoryOther', 'accessoryNothing'],
    ['carryingBackpack', 'carryingHandbag', 'carryingLuggageCase', 'carryingOutwear', 'carryingShoppingBag', 'carryingShoulderBag', 'carryingUmbrella', 'carryingOther', 'carryingNothing'],
    ['upperBodyBlack', 'upperBodyBlue', 'upperBodyBrown', 'upperBodyGreen', 'upperBodyGrey', 'upperBodyOrange', 'upperBodyPink', 'upperBodyPurple', 'upperBodyRed', 'upperBodyWhite', 'upperBodyYellow', 'upperBodyOtherColor'],
    ['upperBodyCoat', 'upperBodyDownCoat', 'upperBodyDress', 'upperBodyJacket', 'upperBodyShirt', 'upperBodySweater', 'upperBodySuit', 'upperBodyTshirt', 'upperBodyOtherStyle']
]

multival_titles = [
    'Accessories',
    'Carryings',
    'Upper Body Colors',
    'Upper Body Styles'
]
