#!/bin/sh
# -*- coding: utf-8 -*-


print_usage() {
    echo "Usage: ./run command"
    echo "Commands:"
    echo "    viewer"
    echo "        Open the data viewer"
    echo ""
}

PY=python
if hash python2 2>/dev/null; then
    PY=python2
fi

if [ $# -eq 0 ]; then
    print_usage
else
    if [ $1 == "viewer" ]; then
        $PY ../reid/utils/data_viewer.py
    else
        print_usage
    fi
fi

